### ISSUE TITLE
i am new this modding, can use somehelp

### ISSUE THREAD

**Issue by itabs500** [ModTheGungeon/ETGMod.Installer.Citrus#1]
ETGMod Installer v16.8.3.0
No previous mod installation found.
Still reverting to unmodded backup...
Reverting: EtG.exe
Reverting: Assembly-CSharp.dll
Reverting: UnityEngine.dll
Reloading Assembly-CSharp.dll
Clearing mod cache...
Removing: Assembly-CSharp.dll.deobfuscated
Removing: Assembly-CSharp.dll.deobfuscated.sum
Entering the Modgeon
No previous mod installation found.
Still reverting to unmodded backup...
Reverting: EtG.exe
WARNING: Backup not found for EtG.exe
Reloading Assembly-CSharp.dll
Backing up: UnityEngine.dll
Backing up: Assembly-CSharp.dll
Backing up: EtG.exe
de4dot already existing, not extracting.
Deobfuscating Assembly-CSharp.dll with de4dot.
C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\de4dot.exe -f "C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\Assembly-CSharp.dll" -o "C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\Assembly-CSharp.dll.deobfuscated"

de4dot v3.1.41592.3405 Copyright (C) 2011-2015 de4dot@gmail.com
Latest version and source code: https://github.com/0xd4d/de4dot

Detected Unknown Obfuscator (C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\Assembly-CSharp.dll)
Cleaning C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\Assembly-CSharp.dll
Renaming all obfuscated symbols
Saving C:\Program Files (x86)\Steam\SteamApps\common\Enter the Gungeon\EtG_Data\Managed\Assembly-CSharp.dll.deobfuscated

Mod #0: Base
Downloading http://modthegungeon.github.io/ETGMOD.zip...
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.OpenRead(Uri address)
   at System.Net.WebClient.OpenRead(String address)
   at ETGModInstaller.ETGModder.Download(InstallerWindow ins, String url)
   at ETGModInstaller.ETGModder.DownloadCached(InstallerWindow ins, String url, String cached)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

**Comment by 0x0ade** [comment]
```
Mod #0: Base
Downloading http://modthegungeon.github.io/ETGMOD.zip...
System.Net.WebException: The remote server returned an error: (403) Forbidden.
```

Seems like GitHub didn't want to give you the file at that moment. Try again.

If it keeps failing, download the file manually, enable offline mode (advanced tab) and drag-n-drop the .zip in.

**Comment by itabs500** [comment]
hey, took me some time to find the file and download it but i did as you said and it worked. thanks
